// Mock data for app demonstration
const mockData = {
  // --- Users ---
  users: [
    {
      id: 'u1',
      name: 'Rajesh Sharma',
      mobile: '9876543210',
      email: 'rajesh@example.com',
      role: 'admin',
      societyId: 's1',
      avatar: null,
    },
    {
      id: 'u2',
      name: 'Priya Patel',
      mobile: '9876543211',
      email: 'priya@example.com',
      role: 'resident',
      societyId: 's1',
      flatId: 'f1',
      avatar: null,
      bankingDetails: {
        accountHolder: 'Priya Patel',
        bankName: 'HDFC Bank',
        accountNumber: '1234567890123',
        ifsc: 'HDFC0001234',
        upiId: 'priya@hdfc',
      },
    },
    {
      id: 'u3',
      name: 'Amit Kumar',
      mobile: '9876543212',
      email: 'amit@example.com',
      role: 'resident',
      societyId: 's1',
      flatId: 'f2',
      avatar: null,
      bankingDetails: null,
    },
    {
      id: 'u4',
      name: 'Sneha Reddy',
      mobile: '9876543213',
      email: 'sneha@example.com',
      role: 'resident',
      societyId: 's1',
      flatId: 'f3',
      avatar: null,
      bankingDetails: null,
    },
    {
      id: 'u5',
      name: 'Vikram Singh',
      mobile: '9876543214',
      email: 'vikram@example.com',
      role: 'tenant',
      societyId: 's1',
      flatId: 'f5',
      avatar: null,
      bankingDetails: null,
    },
    {
      id: 'u6',
      name: 'Deepak Joshi',
      mobile: '9876543215',
      email: 'deepak@example.com',
      role: 'manager',
      societyId: 's1',
      avatar: null,
    },
    {
      id: 'u7',
      name: 'Ramesh Gupta',
      mobile: '9876543216',
      email: 'ramesh@example.com',
      role: 'security',
      societyId: 's1',
      avatar: null,
    },
  ],

  // --- Society ---
  society: {
    id: 's1',
    name: 'Sunrise Heights',
    address: '123, MG Road, Pune, Maharashtra 411001',
    bankDetails: {
      bankName: 'State Bank of India',
      accountNumber: '1234567890',
      ifsc: 'SBIN0001234',
      accountHolder: 'Sunrise Heights CHS',
    },
    upiId: 'sunriseheights@sbi',
    qrCode: null,
    createdAt: '2025-01-01',
  },

  // --- Buildings ---
  buildings: [
    { id: 'b1', name: 'A Wing', societyId: 's1', floors: 5 },
    { id: 'b2', name: 'B Wing', societyId: 's1', floors: 5 },
  ],

  // --- Flats ---
  flats: [
    { id: 'f1', flatNumber: 'A-101', building: 'A Wing', floor: 1, areaSqft: 850, societyId: 's1', residentId: 'u2', status: 'occupied' },
    { id: 'f2', flatNumber: 'A-102', building: 'A Wing', floor: 1, areaSqft: 1050, societyId: 's1', residentId: 'u3', status: 'occupied' },
    { id: 'f3', flatNumber: 'A-201', building: 'A Wing', floor: 2, areaSqft: 850, societyId: 's1', residentId: 'u4', status: 'occupied' },
    { id: 'f4', flatNumber: 'A-202', building: 'A Wing', floor: 2, areaSqft: 1050, societyId: 's1', residentId: null, status: 'vacant' },
    { id: 'f5', flatNumber: 'B-101', building: 'B Wing', floor: 1, areaSqft: 950, societyId: 's1', residentId: 'u5', status: 'occupied' },
    { id: 'f6', flatNumber: 'B-102', building: 'B Wing', floor: 1, areaSqft: 950, societyId: 's1', residentId: null, status: 'vacant' },
    { id: 'f7', flatNumber: 'A-301', building: 'A Wing', floor: 3, areaSqft: 850, societyId: 's1', residentId: null, status: 'vacant' },
    { id: 'f8', flatNumber: 'A-302', building: 'A Wing', floor: 3, areaSqft: 1050, societyId: 's1', residentId: null, status: 'vacant' },
    { id: 'f9', flatNumber: 'B-201', building: 'B Wing', floor: 2, areaSqft: 950, societyId: 's1', residentId: null, status: 'vacant' },
    { id: 'f10', flatNumber: 'B-202', building: 'B Wing', floor: 2, areaSqft: 950, societyId: 's1', residentId: null, status: 'vacant' },
  ],

  // --- Charges ---
  charges: [
    { id: 'ch1', name: 'Maintenance', amount: 3000, type: 'fixed' },
    { id: 'ch2', name: 'Water Charge', amount: 500, type: 'fixed' },
    { id: 'ch3', name: 'Lift Maintenance', amount: 300, type: 'fixed' },
    { id: 'ch4', name: 'Sinking Fund', amount: 500, type: 'fixed' },
    { id: 'ch5', name: 'Repair Fund', amount: 200, type: 'fixed' },
  ],

  // --- Vehicles ---
  vehicles: [
    { id: 'v1', flatId: 'f1', flatNumber: 'A-101', residentId: 'u2', residentName: 'Priya Patel', vehicleNumber: 'MH 12 AB 1234', type: 'four_wheeler', make: 'Hyundai Creta', color: 'White', parkingSlot: 'P-A01', monthlyCharge: 500 },
    { id: 'v2', flatId: 'f1', flatNumber: 'A-101', residentId: 'u2', residentName: 'Priya Patel', vehicleNumber: 'MH 12 CD 5678', type: 'two_wheeler', make: 'Honda Activa', color: 'Black', parkingSlot: 'T-A01', monthlyCharge: 200 },
    { id: 'v3', flatId: 'f2', flatNumber: 'A-102', residentId: 'u3', residentName: 'Amit Kumar', vehicleNumber: 'MH 14 EF 9012', type: 'four_wheeler', make: 'Maruti Swift', color: 'Red', parkingSlot: 'P-A02', monthlyCharge: 500 },
    { id: 'v4', flatId: 'f3', flatNumber: 'A-201', residentId: 'u4', residentName: 'Sneha Reddy', vehicleNumber: 'MH 12 GH 3456', type: 'two_wheeler', make: 'TVS Jupiter', color: 'Blue', parkingSlot: 'T-A03', monthlyCharge: 200 },
    { id: 'v5', flatId: 'f5', flatNumber: 'B-101', residentId: 'u5', residentName: 'Vikram Singh', vehicleNumber: 'MH 14 IJ 7890', type: 'four_wheeler', make: 'Tata Nexon', color: 'Grey', parkingSlot: 'P-B01', monthlyCharge: 500 },
    { id: 'v6', flatId: 'f5', flatNumber: 'B-101', residentId: 'u5', residentName: 'Vikram Singh', vehicleNumber: 'MH 14 KL 1122', type: 'two_wheeler', make: 'Royal Enfield', color: 'Black', parkingSlot: 'T-B01', monthlyCharge: 200 },
  ],

  // --- Visitors ---
  visitors: [
    {
      id: 'vis1',
      visitorName: 'Rahul Mehta',
      phone: '9988776655',
      purpose: 'Guest',
      visitingFlat: 'A-101',
      visitingResident: 'Priya Patel',
      vehicleNumber: 'MH 12 XY 9999',
      checkedInAt: '2026-04-08T09:30:00',
      checkedOutAt: '2026-04-08T12:45:00',
      status: 'checked_out',
      checkedInBy: 'u7',
      notes: '',
    },
    {
      id: 'vis2',
      visitorName: 'Swiggy Delivery',
      phone: '9900112233',
      purpose: 'Delivery',
      visitingFlat: 'A-102',
      visitingResident: 'Amit Kumar',
      vehicleNumber: 'MH 14 DL 1234',
      checkedInAt: '2026-04-08T13:00:00',
      checkedOutAt: '2026-04-08T13:15:00',
      status: 'checked_out',
      checkedInBy: 'u7',
      notes: 'Food delivery',
    },
    {
      id: 'vis3',
      visitorName: 'Suresh Electrician',
      phone: '9811223344',
      purpose: 'Maintenance',
      visitingFlat: 'A-201',
      visitingResident: 'Sneha Reddy',
      vehicleNumber: '',
      checkedInAt: '2026-04-08T10:00:00',
      checkedOutAt: null,
      status: 'checked_in',
      checkedInBy: 'u7',
      notes: 'Electrical repair work',
    },
    {
      id: 'vis4',
      visitorName: 'Anita Sharma',
      phone: '9876000111',
      purpose: 'Guest',
      visitingFlat: 'B-101',
      visitingResident: 'Vikram Singh',
      vehicleNumber: 'MH 02 AB 5555',
      checkedInAt: '2026-04-08T14:30:00',
      checkedOutAt: null,
      status: 'checked_in',
      checkedInBy: 'u7',
      notes: 'Family visit',
    },
    {
      id: 'vis5',
      visitorName: 'Ola Cab',
      phone: '9999888777',
      purpose: 'Cab / Taxi',
      visitingFlat: 'A-101',
      visitingResident: 'Priya Patel',
      vehicleNumber: 'MH 12 OL 4321',
      checkedInAt: '2026-04-07T18:00:00',
      checkedOutAt: '2026-04-07T18:10:00',
      status: 'checked_out',
      checkedInBy: 'u7',
      notes: '',
    },
  ],

  // --- Bills ---
  bills: [
    {
      id: 'bill1',
      flatId: 'f1',
      flatNumber: 'A-101',
      residentName: 'Priya Patel',
      residentId: 'u2',
      month: 2,
      year: 2026,
      charges: [
        { name: 'Maintenance', amount: 3000 },
        { name: 'Water Charge', amount: 500 },
        { name: 'Parking (4W - MH 12 AB 1234)', amount: 500 },
        { name: 'Parking (2W - MH 12 CD 5678)', amount: 200 },
        { name: 'Sinking Fund', amount: 500 },
      ],
      totalAmount: 4700,
      dueDate: '2026-03-15',
      previousDue: 0,
      lateFee: 0,
      status: 'paid',
      createdAt: '2026-03-01',
    },
    {
      id: 'bill2',
      flatId: 'f2',
      flatNumber: 'A-102',
      residentName: 'Amit Kumar',
      residentId: 'u3',
      month: 2,
      year: 2026,
      charges: [
        { name: 'Maintenance', amount: 3500 },
        { name: 'Water Charge', amount: 500 },
        { name: 'Parking (4W - MH 14 EF 9012)', amount: 500 },
        { name: 'Lift Maintenance', amount: 300 },
        { name: 'Sinking Fund', amount: 500 },
      ],
      totalAmount: 5300,
      dueDate: '2026-03-15',
      previousDue: 0,
      lateFee: 0,
      status: 'pending_verification',
      createdAt: '2026-03-01',
    },
    {
      id: 'bill3',
      flatId: 'f3',
      flatNumber: 'A-201',
      residentName: 'Sneha Reddy',
      residentId: 'u4',
      month: 2,
      year: 2026,
      charges: [
        { name: 'Maintenance', amount: 3000 },
        { name: 'Water Charge', amount: 500 },
        { name: 'Parking (2W - MH 12 GH 3456)', amount: 200 },
        { name: 'Sinking Fund', amount: 500 },
      ],
      totalAmount: 4200,
      dueDate: '2026-03-15',
      previousDue: 0,
      lateFee: 200,
      status: 'unpaid',
      createdAt: '2026-03-01',
    },
    {
      id: 'bill4',
      flatId: 'f1',
      flatNumber: 'A-101',
      residentName: 'Priya Patel',
      residentId: 'u2',
      month: 3,
      year: 2026,
      charges: [
        { name: 'Maintenance', amount: 3000 },
        { name: 'Water Charge', amount: 500 },
        { name: 'Parking (4W - MH 12 AB 1234)', amount: 500 },
        { name: 'Parking (2W - MH 12 CD 5678)', amount: 200 },
        { name: 'Sinking Fund', amount: 500 },
      ],
      totalAmount: 4700,
      dueDate: '2026-04-15',
      previousDue: 0,
      lateFee: 0,
      status: 'unpaid',
      createdAt: '2026-04-01',
    },
    {
      id: 'bill5',
      flatId: 'f5',
      flatNumber: 'B-101',
      residentName: 'Vikram Singh',
      residentId: 'u5',
      month: 2,
      year: 2026,
      charges: [
        { name: 'Maintenance', amount: 3200 },
        { name: 'Water Charge', amount: 500 },
        { name: 'Parking (4W - MH 14 IJ 7890)', amount: 500 },
        { name: 'Parking (2W - MH 14 KL 1122)', amount: 200 },
      ],
      totalAmount: 4400,
      dueDate: '2026-03-15',
      previousDue: 0,
      lateFee: 0,
      status: 'paid',
      createdAt: '2026-03-01',
    },
  ],

  // --- Payments ---
  payments: [
    {
      id: 'pay1',
      billId: 'bill1',
      userId: 'u2',
      userName: 'Priya Patel',
      flatNumber: 'A-101',
      amount: 4700,
      paymentMethod: 'upi',
      transactionId: 'UPI123456789',
      appName: 'Google Pay',
      bankName: 'HDFC Bank',
      accountNumber: '****0123',
      screenshot: null,
      status: 'approved',
      submittedAt: '2026-03-10',
      verifiedBy: 'u1',
      verifiedByName: 'Rajesh Sharma',
      verifiedAt: '2026-03-10',
      comment: 'Payment verified',
    },
    {
      id: 'pay2',
      billId: 'bill2',
      userId: 'u3',
      userName: 'Amit Kumar',
      flatNumber: 'A-102',
      amount: 5300,
      paymentMethod: 'bank_transfer',
      referenceNumber: 'NEFT2026030112345',
      bankName: 'HDFC Bank',
      accountNumber: '****5678',
      screenshot: null,
      status: 'pending_verification',
      submittedAt: '2026-03-12',
      verifiedBy: null,
      verifiedByName: null,
      verifiedAt: null,
      comment: null,
    },
    {
      id: 'pay3',
      billId: 'bill5',
      userId: 'u5',
      userName: 'Vikram Singh',
      flatNumber: 'B-101',
      amount: 4400,
      paymentMethod: 'cheque',
      chequeNumber: 'CHQ456789',
      bankName: 'ICICI Bank',
      chequeDate: '2026-03-08',
      screenshot: null,
      status: 'approved',
      submittedAt: '2026-03-08',
      verifiedBy: 'u1',
      verifiedByName: 'Rajesh Sharma',
      verifiedAt: '2026-03-09',
      comment: 'Cheque cleared',
    },
  ],

  // --- Expenses ---
  expenses: [
    { id: 'exp1', title: 'Electricity Bill', amount: 25000, category: 'Electricity', date: '2026-03-05', receipt: null },
    { id: 'exp2', title: 'Watchman Salary', amount: 18000, category: 'Staff Salary', date: '2026-03-01', receipt: null },
    { id: 'exp3', title: 'Garden Maintenance', amount: 5000, category: 'Cleaning', date: '2026-03-10', receipt: null },
    { id: 'exp4', title: 'Lift Repair', amount: 12000, category: 'Repair', date: '2026-02-28', receipt: null },
  ],

  // --- Complaints ---
  complaints: [
    {
      id: 'comp1',
      userId: 'u2',
      userName: 'Priya Patel',
      flatNumber: 'A-101',
      title: 'Water leakage in bathroom',
      description: 'There is continuous water leakage from the ceiling of master bathroom.',
      category: 'Plumbing',
      status: 'in_progress',
      image: null,
      adminResponse: 'Plumber has been sent. Will be fixed by tomorrow.',
      createdAt: '2026-03-15',
    },
    {
      id: 'comp2',
      userId: 'u3',
      userName: 'Amit Kumar',
      flatNumber: 'A-102',
      title: 'Parking dispute',
      description: 'Someone is regularly parking in my assigned parking spot B-12.',
      category: 'Parking',
      status: 'open',
      image: null,
      adminResponse: null,
      createdAt: '2026-03-18',
    },
  ],

  // --- Notices ---
  notices: [
    {
      id: 'n1',
      title: 'Annual General Meeting',
      content: 'The AGM will be held on April 15, 2026 at 6 PM in the community hall. All members are requested to attend.',
      priority: 'high',
      createdAt: '2026-04-01',
      createdBy: 'u1',
    },
    {
      id: 'n2',
      title: 'Water Supply Disruption',
      content: 'Water supply will be disrupted on April 5, 2026 from 10 AM to 4 PM due to maintenance work. Please store water accordingly.',
      priority: 'medium',
      createdAt: '2026-04-03',
      createdBy: 'u1',
    },
    {
      id: 'n3',
      title: 'Diwali Celebration',
      content: 'Society Diwali celebration will be held on Nov 1st. Contributions welcome. Contact the committee for details.',
      priority: 'low',
      createdAt: '2026-03-28',
      createdBy: 'u1',
    },
  ],

  // --- Notifications ---
  notifications: [
    { id: 'notif1', type: 'bill', title: 'New Bill Generated', message: 'Your maintenance bill for April 2026 has been generated.', read: false, createdAt: '2026-04-01T10:00:00', userId: 'u2' },
    { id: 'notif2', type: 'payment', title: 'Payment Approved', message: 'Your payment of ₹4,700 for March 2026 has been approved.', read: true, createdAt: '2026-03-10T14:30:00', userId: 'u2' },
    { id: 'notif3', type: 'payment_received', title: 'New Payment Submitted', message: 'Amit Kumar (A-102) has submitted payment of ₹5,300.', read: false, createdAt: '2026-03-12T09:15:00', userId: 'u1' },
    { id: 'notif4', type: 'complaint', title: 'New Complaint', message: 'Amit Kumar has raised a complaint about parking.', read: false, createdAt: '2026-03-18T11:00:00', userId: 'u1' },
    { id: 'notif5', type: 'visitor', title: 'Visitor Checked In', message: 'Visitor Anita Sharma checked in to visit B-101.', read: false, createdAt: '2026-04-08T14:30:00', userId: 'u5' },
  ],
};

export default mockData;
